version = 3
final_space = true
console_title_template = '{{ .Shell }} in {{ .Folder }}'


[palette]
  dark_grey = '#6c6c6c'


[upgrade]
  source = 'cdn'
  interval = '168h'
  auto = false
  notice = true


[transient_prompt]
  background = "transparent"
  foreground_templates = [
    "{{ if gt .Code 0 }}red{{end}}",
    "{{ if eq .Code 0 }}magenta{{end}}"
  ]
  template = "❯ "


[secondary_prompt]
  background = "transparent"
  foreground = "magenta"
  template = "❯❯ "


[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    type = "os"
    style = "diamond"
    background = "blue"
    leading_diamond = " "
    trailing_diamond = " "
    template = "{{.Icon}} "

  [[blocks.segments]]
    type = 'path'
    style = 'plain'
    background = 'transparent'
    foreground = 'blue'
    template = '{{ .Path }}'

    [blocks.segments.properties]
      style = 'full'

  [[blocks.segments]]
    type = 'git'
    style = 'plain'
    background = 'transparent'
    foreground = 'p:dark_grey'
    templates = [
      ' {{ .HEAD }}{{ if or (.Working.Changed) (.Staging.Changed) }}*{{end}} ',
      '<cyan>{{ if gt .Behind 0 }}{{end}}</>',
      '<cyan>{{ if gt .Ahead 0 }}{{end}}</>',
    ]

    [blocks.segments.properties]
      branch_icon = ''
      commit_icon = '@'
      fetch_status = true
  
[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    type = 'text'
    style = 'plain'
    background = 'transparent'
    foreground_templates = [
      "{{ if gt .Code 0 }}red{{end}}",
      "{{ if eq .Code 0 }}magenta{{end}}"
    ]
    template = '❯'

[[blocks]]
  type = 'rprompt'
  overflow = 'hidden'

  [[blocks.segments]]
    type = 'executiontime'
    style = 'plain'
    background = 'transparent'
    foreground = 'yellow'
    template = '{{ .FormattedMs }}'

    [blocks.segments.properties]
      threshold = 1000